spring:
  application:
    name: appmoments

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

    hikari:
      initialization-fail-timeout: -1
      connection-timeout: 30000
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: ${SPRING_HIBERNATE_DIALECT}

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

#Configs da Aplicação

appmoments:
  albumfolder: ${ALBUM_FOLDER}

api:
  security:
    token:
      secret: ${JWT_SECRET:secret-key}